const dataCompleta = {
  hourlyWeatherVariable: {
    weatherCode: [
      [
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
      ],
      [
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-fog.webp",
        "../../assets/images/icon-fog.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-partly-cloudy.webp",
      ],
      [
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
      ],
      [
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
      ],
      [
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
      ],
      [
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
      ],
      [
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
      ],
    ],
    temperature: [
      [
        22, 22, 21, 21, 21, 20, 20, 20, 21, 22, 24, 25, 26, 28, 29, 29, 29, 28,
        26, 24, 23, 23, 23, 22,
      ],
      [
        21, 21, 21, 21, 21, 20, 20, 19, 21, 23, 25, 27, 28, 29, 30, 30, 30, 29,
        28, 27, 25, 24, 23, 23,
      ],
      [
        23, 23, 23, 23, 23, 22, 22, 23, 23, 24, 26, 28, 30, 31, 33, 33, 33, 32,
        30, 27, 25, 24, 24, 24,
      ],
      [
        23, 23, 23, 23, 23, 23, 23, 23, 25, 26, 28, 30, 32, 33, 35, 35, 34, 32,
        30, 28, 26, 25, 24, 24,
      ],
      [
        24, 23, 23, 23, 22, 22, 22, 23, 23, 25, 27, 29, 31, 32, 32, 33, 32, 31,
        29, 28, 25, 24, 23, 23,
      ],
      [
        23, 23, 23, 23, 22, 22, 22, 22, 23, 24, 24, 25, 25, 25, 25, 25, 25, 26,
        26, 25, 24, 23, 23, 23,
      ],
      [
        22, 22, 22, 22, 22, 21, 21, 22, 23, 25, 26, 28, 30, 31, 31, 31, 31, 31,
        30, 29, 27, 25, 25, 25,
      ],
    ],
  },
  dailyWeatherVariables: {
    weatherCode: [
      "../../assets/images/icon-partly-cloudy.webp",
      "../../assets/images/icon-fog.webp",
      "../../assets/images/icon-partly-cloudy.webp",
      "../../assets/images/icon-partly-cloudy.webp",
      "../../assets/images/icon-overcast.webp",
      "../../assets/images/icon-rain.webp",
      "../../assets/images/icon-overcast.webp",
    ],
    temperatureMean: [24, 24, 26, 27, 26, 24, 26],
    date: [
      ["2026", "3", "14"],
      ["2026", "3", "15"],
      ["2026", "3", "16"],
      ["2026", "3", "17"],
      ["2026", "3", "18"],
      ["2026", "3", "19"],
      ["2026", "3", "20"],
    ],
    location: { city: "Porto Alegre", country: "Brazil" },
    dayMeanDetails: {
      apparentTemperatureMean: [26, 27, 29, 30, 29, 27, 29],
      relativeHumidity: [73, 77, 78, 71, 75, 83, 73],
      windSpeed: [7, 9, 12, 10, 11, 9, 8],
      precipitationMean: [0, 0, 0, 0, 3, 11, 15],
    },
    dailyForecast: {
      temperatureMax: [29, 30, 33, 35, 33, 26, 31],
      temperatureMin: [20, 19, 22, 23, 22, 22, 21],
    },
  },
};
