const dataCompleta = {
  hourlyWeatherVariable: {
    weatherCode: [
      [
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-fog.webp",
        "../../assets/images/icon-fog.webp",
        "../../assets/images/icon-fog.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
      ],
      [
        "../../assets/images/icon-fog.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-fog.webp",
        "../../assets/images/icon-overcast.webp",
      ],
      [
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-rain.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
      ],
      [
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
      ],
      [
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
      ],
      [
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
      ],
      [
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-partly-cloudy.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-sunny.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-storm.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
        "../../assets/images/icon-overcast.webp",
      ],
    ],
    temperature: [
      [
        22, 22, 22, 21, 21, 21, 20, 21, 25, 25, 27, 28, 29, 30, 30, 31, 31, 29,
        27, 25, 24, 24, 23, 23,
      ],
      [
        22, 22, 22, 21, 21, 20, 20, 20, 24, 26, 27, 28, 29, 30, 31, 29, 27, 26,
        25, 24, 24, 23, 23, 23,
      ],
      [
        23, 22, 22, 22, 21, 21, 21, 21, 25, 26, 27, 28, 29, 30, 28, 27, 26, 25,
        25, 24, 23, 23, 23, 23,
      ],
      [
        23, 22, 22, 22, 21, 21, 20, 21, 24, 25, 27, 28, 29, 30, 30, 29, 28, 27,
        25, 24, 23, 23, 23, 23,
      ],
      [
        22, 22, 21, 20, 20, 20, 19, 20, 22, 25, 27, 28, 29, 29, 29, 29, 28, 27,
        27, 26, 25, 24, 24, 23,
      ],
      [
        22, 22, 21, 21, 20, 20, 20, 20, 22, 25, 27, 29, 30, 30, 30, 30, 29, 28,
        26, 25, 24, 24, 23, 23,
      ],
      [
        22, 22, 22, 21, 21, 21, 21, 21, 23, 26, 28, 29, 30, 31, 30, 28, 27, 26,
        25, 25, 24, 24, 23, 23,
      ],
    ],
  },
  dailyWeatherVariables: {
    weatherCode: [
      "../../assets/images/icon-fog.webp",
      "../../assets/images/icon-storm.webp",
      "../../assets/images/icon-storm.webp",
      "../../assets/images/icon-storm.webp",
      "../../assets/images/icon-overcast.webp",
      "../../assets/images/icon-overcast.webp",
      "../../assets/images/icon-storm.webp",
    ],
    temperatureMean: [25, 25, 24, 25, 24, 25, 25],
    date: [
      ["2026", "3", "18"],
      ["2026", "3", "19"],
      ["2026", "3", "20"],
      ["2026", "3", "21"],
      ["2026", "3", "22"],
      ["2026", "3", "23"],
      ["2026", "3", "24"],
    ],
    location: {
      city: ["Singapura'", "Singapura"],
      state: ["West Java", "South Sumatra"],
      country: ["Indonesia", "Indonesia"],
    },
    dayMeanDetails: {
      apparentTemperatureMean: [29, 29, 29, 29, 28, 28, 29],
      relativeHumidity: [79, 82, 86, 84, 79, 79, 83],
      windSpeed: [4, 4, 4, 5, 5, 4, 3],
      precipitationMean: [8, 18, 25, 20, 17, 19, 27],
    },
    dailyForecast: {
      temperatureMax: [31, 31, 30, 30, 29, 30, 31],
      temperatureMin: [20, 20, 21, 20, 19, 20, 21],
    },
  },
};
const cordinates = {
  results: [
    {
      id: 1949608,
      name: "Singapura",
      latitude: -6.8,
      longitude: 107.42139,
      elevation: 490,
      feature_code: "PPL",
      country_code: "ID",
      admin1_id: 1642672,
      admin2_id: 7910336,
      timezone: "Asia/Jakarta",
      country_id: 1643084,
      country: "Indonesia",
      admin1: "West Java",
      admin2: "West Bandung Regency",
    },
    {
      id: 6779833,
      name: "Singapura",
      latitude: -6.6532,
      longitude: 108.5299,
      elevation: 5,
      feature_code: "PPL",
      country_code: "ID",
      admin1_id: 1642672,
      admin2_id: 1646169,
      timezone: "Asia/Jakarta",
      country_id: 1643084,
      country: "Indonesia",
      admin1: "West Java",
      admin2: "Cirebon Regency",
    },
    {
      id: 8364875,
      name: "Singapura",
      latitude: -4.08572,
      longitude: 104.05537,
      elevation: 66,
      feature_code: "PPL",
      country_code: "ID",
      admin1_id: 1626196,
      admin2_id: 1633658,
      timezone: "Asia/Jakarta",
      country_id: 1643084,
      country: "Indonesia",
      admin1: "South Sumatra",
      admin2: "Kabupaten Ogan Komering Ulu",
    },
    {
      id: 8471402,
      name: "Singapura",
      latitude: -3.5593,
      longitude: 103.2922,
      elevation: 65,
      feature_code: "PPL",
      country_code: "ID",
      admin1_id: 1626196,
      admin2_id: 9166049,
      timezone: "Asia/Jakarta",
      country_id: 1643084,
      country: "Indonesia",
      admin1: "South Sumatra",
      admin2: "Lahat Regency",
    },
  ],
  generationtime_ms: 0.7234812,
};

const citys = {
  results: [
    {
      id: 3452925,
      name: "Porto Alegre",
      latitude: -30.03283,
      longitude: -51.23019,
      elevation: 46,
      feature_code: "PPLA",
      country_code: "BR",
      admin1_id: 3451133,
      admin2_id: 6323571,
      timezone: "America/Sao_Paulo",
      population: 1488252,
      country_id: 3469034,
      country: "Brazil",
      admin1: "Rio Grande do Sul",
      admin2: "Porto Alegre",
    },
    {
      id: 3391401,
      name: "Porto Alegre do Piauí",
      latitude: -6.97091,
      longitude: -44.1983,
      elevation: 159,
      feature_code: "PPLA2",
      country_code: "BR",
      admin1_id: 3392213,
      admin2_id: 6319980,
      timezone: "America/Fortaleza",
      population: 2364,
      country_id: 3469034,
      country: "Brazil",
      admin1: "Piauí",
      admin2: "Porto Alegre do Piauí",
    },
    {
      id: 3456593,
      name: "Mucuri",
      latitude: -18.08639,
      longitude: -39.55083,
      elevation: 7,
      feature_code: "PPL",
      country_code: "BR",
      admin1_id: 3471168,
      admin2_id: 6320966,
      timezone: "America/Bahia",
      population: 37977,
      country_id: 3469034,
      country: "Brazil",
      admin1: "Estado de Bahia",
      admin2: "Mucuri",
    },
    {
      id: 3396101,
      name: "Luzilândia",
      latitude: -3.45778,
      longitude: -42.37028,
      elevation: 39,
      feature_code: "PPL",
      country_code: "BR",
      admin1_id: 3392213,
      admin2_id: 6319939,
      timezone: "America/Fortaleza",
      population: 25375,
      country_id: 3469034,
      country: "Brazil",
      admin1: "Piauí",
      admin2: "Luzilândia",
    },
  ],
  generationtime_ms: 0.8711815,
};
